server:
    port: 8081
logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/jeesite
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    dubbo:
        app : dubbo-user-provider
        registry : zookeeper://127.0.0.1:2181
        protocol : dubbo
        port : 6379

